[build]
builder = "DOCKERFILE"
dockerfilePath = "server.Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = true
useLegacyStacker = false
multiRegionConfig = {"us-east4-eqdc4a" = {"numReplicas" = 1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10